name: Refresh ATT&CK data
on:
  schedule:
    - cron:  '0 */12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Checkout the Wiki
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./editor/script/requirements.txt

      - name: Refresh ATT&CK data (JSON files and Wiki)
        working-directory: ./editor/script
        run: |
          python refresh_attack_data.py

      - name: JSON data - check for changes
        id: changesjson
        run: |
          OUTPUT=`git status`
          echo ::set-output name=GIT_STATUS_CODE::${OUTPUT}
          echo $OUTPUT

      - name: JSON data - commit files (if applicable)
        if: contains(steps.changesjson.outputs.GIT_STATUS_CODE, 'modified')
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Refresh ATT&CK json data files"

      - name: JSON data - push changes (if applicable)
        if: contains(steps.changesjson.outputs.GIT_STATUS_CODE, 'modified')
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Wiki - check for changes
        id: changeswiki
        working-directory: ./wiki
        run: |
          OUTPUT=`git status`
          echo ::set-output name=GIT_STATUS_WIKI::${OUTPUT}
          echo $OUTPUT

      - name: Wiki - commit files (if applicable)
        if: contains(steps.changeswiki.outputs.GIT_STATUS_WIKI, 'modified')
        working-directory: ./wiki
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update Wiki help texts"

      - name: Wiki - push changes (if applicable)
        if: contains(steps.changeswiki.outputs.GIT_STATUS_WIKI, 'modified')
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "wiki"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
